name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Build
        run: |
          npm run build

      - name: Push to github.io
        run: |
          cd ./dist
          git init
          git config --global user.name ${{ github.actor }}
          git config --global user.email ${{ github.actor }}@users.noreply.github.com
          git add .
          git commit -m "deloy"
          git branch -M main
          git remote add origin https://${{ github.actor }}:${{ secrets.GH_TOKEN }}@github.com/jaemin-s/jaemin-s.github.io.git
          git push -f origin main
